// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomepageDocumentDataSlicesSlice = HeroSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
   /**
    * Slice Zone field in *Homepage*
    *
    * - **Field Type**: Slice Zone
    * - **Placeholder**: *None*
    * - **API ID Path**: homepage.slices[]
    * - **Tab**: Main
    * - **Documentation**: https://prismic.io/docs/field#slices
    */
   slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
    * Meta Title field in *Homepage*
    *
    * - **Field Type**: Text
    * - **Placeholder**: A title of the page used for social media and search engines
    * - **API ID Path**: homepage.meta_title
    * - **Tab**: SEO & Metadata
    * - **Documentation**: https://prismic.io/docs/field#key-text
    */;
   meta_title: prismic.KeyTextField;

   /**
    * Meta Description field in *Homepage*
    *
    * - **Field Type**: Text
    * - **Placeholder**: A brief summary of the page
    * - **API ID Path**: homepage.meta_description
    * - **Tab**: SEO & Metadata
    * - **Documentation**: https://prismic.io/docs/field#key-text
    */
   meta_description: prismic.KeyTextField;

   /**
    * Meta Image field in *Homepage*
    *
    * - **Field Type**: Image
    * - **Placeholder**: *None*
    * - **API ID Path**: homepage.meta_image
    * - **Tab**: SEO & Metadata
    * - **Documentation**: https://prismic.io/docs/field#image
    */
   meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
   Simplify<HomepageDocumentData>,
   'homepage',
   Lang
>;

/**
 * Item in *Setting → Navigation*
 */
export interface SettinsDocumentDataNavigationItem {
   /**
    * Title field in *Setting → Navigation*
    *
    * - **Field Type**: Text
    * - **Placeholder**: *None*
    * - **API ID Path**: settins.navigation[].title
    * - **Documentation**: https://prismic.io/docs/field#key-text
    */
   title: prismic.KeyTextField;

   /**
    * Link field in *Setting → Navigation*
    *
    * - **Field Type**: Link
    * - **Placeholder**: *None*
    * - **API ID Path**: settins.navigation[].link
    * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
    */
   link: prismic.LinkField;

   /**
    * Icon field in *Setting → Navigation*
    *
    * - **Field Type**: Select
    * - **Placeholder**: *None*
    * - **API ID Path**: settins.navigation[].icon
    * - **Documentation**: https://prismic.io/docs/field#select
    */
   icon: prismic.SelectField<'flight' | 'hotel' | 'tour' | 'car'>;

   /**
    * Description field in *Setting → Navigation*
    *
    * - **Field Type**: Text
    * - **Placeholder**: *None*
    * - **API ID Path**: settins.navigation[].description
    * - **Documentation**: https://prismic.io/docs/field#key-text
    */
   description: prismic.KeyTextField;
}

/**
 * Item in *Setting → Host*
 */
export interface SettinsDocumentDataHostItem {
   /**
    * Label field in *Setting → Host*
    *
    * - **Field Type**: Text
    * - **Placeholder**: *None*
    * - **API ID Path**: settins.host[].label
    * - **Documentation**: https://prismic.io/docs/field#key-text
    */
   label: prismic.KeyTextField;

   /**
    * Address field in *Setting → Host*
    *
    * - **Field Type**: Text
    * - **Placeholder**: *None*
    * - **API ID Path**: settins.host[].address
    * - **Documentation**: https://prismic.io/docs/field#key-text
    */
   address: prismic.KeyTextField;

   /**
    * Active time field in *Setting → Host*
    *
    * - **Field Type**: Text
    * - **Placeholder**: *None*
    * - **API ID Path**: settins.host[].active_time
    * - **Documentation**: https://prismic.io/docs/field#key-text
    */
   active_time: prismic.KeyTextField;

   /**
    * Mail field in *Setting → Host*
    *
    * - **Field Type**: Text
    * - **Placeholder**: *None*
    * - **API ID Path**: settins.host[].mail
    * - **Documentation**: https://prismic.io/docs/field#key-text
    */
   mail: prismic.KeyTextField;
}

/**
 * Item in *Setting → Socials*
 */
export interface SettinsDocumentDataSocialsItem {
   /**
    * Icon field in *Setting → Socials*
    *
    * - **Field Type**: Select
    * - **Placeholder**: *None*
    * - **API ID Path**: settins.socials[].icon
    * - **Documentation**: https://prismic.io/docs/field#select
    */
   icon: prismic.SelectField<'facebook' | 'instagram' | 'twitter' | 'youtube'>;

   /**
    * Link field in *Setting → Socials*
    *
    * - **Field Type**: Link
    * - **Placeholder**: *None*
    * - **API ID Path**: settins.socials[].link
    * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
    */
   link: prismic.LinkField;
}

/**
 * Item in *Setting → Footers*
 */
export interface SettinsDocumentDataFootersItem {}

type SettinsDocumentDataSlicesSlice = never;

/**
 * Content for Setting documents
 */
interface SettinsDocumentData {
   /**
    * Logo field in *Setting*
    *
    * - **Field Type**: Image
    * - **Placeholder**: *None*
    * - **API ID Path**: settins.logo
    * - **Tab**: Main
    * - **Documentation**: https://prismic.io/docs/field#image
    */
   logo: prismic.ImageField<never>;

   /**
    * Site name field in *Setting*
    *
    * - **Field Type**: Text
    * - **Placeholder**: *None*
    * - **API ID Path**: settins.site_name
    * - **Tab**: Main
    * - **Documentation**: https://prismic.io/docs/field#key-text
    */
   site_name: prismic.KeyTextField;

   /**
    * Navigation field in *Setting*
    *
    * - **Field Type**: Group
    * - **Placeholder**: *None*
    * - **API ID Path**: settins.navigation[]
    * - **Tab**: Main
    * - **Documentation**: https://prismic.io/docs/field#group
    */
   navigation: prismic.GroupField<Simplify<SettinsDocumentDataNavigationItem>>;

   /**
    * Host field in *Setting*
    *
    * - **Field Type**: Group
    * - **Placeholder**: *None*
    * - **API ID Path**: settins.host[]
    * - **Tab**: Main
    * - **Documentation**: https://prismic.io/docs/field#group
    */
   host: prismic.GroupField<Simplify<SettinsDocumentDataHostItem>>;

   /**
    * Socials field in *Setting*
    *
    * - **Field Type**: Group
    * - **Placeholder**: *None*
    * - **API ID Path**: settins.socials[]
    * - **Tab**: Main
    * - **Documentation**: https://prismic.io/docs/field#group
    */
   socials: prismic.GroupField<Simplify<SettinsDocumentDataSocialsItem>>;

   /**
    * Footers field in *Setting*
    *
    * - **Field Type**: Group
    * - **Placeholder**: *None*
    * - **API ID Path**: settins.footers[]
    * - **Tab**: Main
    * - **Documentation**: https://prismic.io/docs/field#group
    */
   footers: prismic.GroupField<Simplify<SettinsDocumentDataFootersItem>>;

   /**
    * Slice Zone field in *Setting*
    *
    * - **Field Type**: Slice Zone
    * - **Placeholder**: *None*
    * - **API ID Path**: settins.slices[]
    * - **Tab**: Main
    * - **Documentation**: https://prismic.io/docs/field#slices
    */
   slices: prismic.SliceZone<SettinsDocumentDataSlicesSlice> /**
    * Meta Title field in *Setting*
    *
    * - **Field Type**: Text
    * - **Placeholder**: A title of the page used for social media and search engines
    * - **API ID Path**: settins.meta_title
    * - **Tab**: SEO & Metadata
    * - **Documentation**: https://prismic.io/docs/field#key-text
    */;
   meta_title: prismic.KeyTextField;

   /**
    * Meta Description field in *Setting*
    *
    * - **Field Type**: Text
    * - **Placeholder**: A brief summary of the page
    * - **API ID Path**: settins.meta_description
    * - **Tab**: SEO & Metadata
    * - **Documentation**: https://prismic.io/docs/field#key-text
    */
   meta_description: prismic.KeyTextField;

   /**
    * Meta Image field in *Setting*
    *
    * - **Field Type**: Image
    * - **Placeholder**: *None*
    * - **API ID Path**: settins.meta_image
    * - **Tab**: SEO & Metadata
    * - **Documentation**: https://prismic.io/docs/field#image
    */
   meta_image: prismic.ImageField<never>;
}

/**
 * Setting document from Prismic
 *
 * - **API ID**: `settins`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettinsDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
   Simplify<SettinsDocumentData>,
   'settins',
   Lang
>;

export type AllDocumentTypes = HomepageDocument | SettinsDocument;

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
   'default',
   Record<string, never>,
   never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<'hero', HeroSliceVariation>;

declare module '@prismicio/client' {
   interface CreateClient {
      (
         repositoryNameOrEndpoint: string,
         options?: prismic.ClientConfig,
      ): prismic.Client<AllDocumentTypes>;
   }

   interface CreateWriteClient {
      (
         repositoryNameOrEndpoint: string,
         options: prismic.WriteClientConfig,
      ): prismic.WriteClient<AllDocumentTypes>;
   }

   interface CreateMigration {
      (): prismic.Migration<AllDocumentTypes>;
   }

   namespace Content {
      export type {
         HomepageDocument,
         HomepageDocumentData,
         HomepageDocumentDataSlicesSlice,
         SettinsDocument,
         SettinsDocumentData,
         SettinsDocumentDataNavigationItem,
         SettinsDocumentDataHostItem,
         SettinsDocumentDataSocialsItem,
         SettinsDocumentDataFootersItem,
         SettinsDocumentDataSlicesSlice,
         AllDocumentTypes,
         HeroSlice,
         HeroSliceVariation,
         HeroSliceDefault,
      };
   }
}
