import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import AppProvider from '@/providers';
import { cn } from '@/lib/utils';

const popins = Poppins({
   subsets: ['latin'],
   variable: '--font-poppins',
   weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en" suppressHydrationWarning>
         <body className={cn(popins.className)}>
            <AppProvider>{children}</AppProvider>
         </body>
      </html>
   );
}
