// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
   ask_and_questions: dynamic(() => import('./AskAndQuestions')),
   explore_stay: dynamic(() => import('./ExploreStay')),
   facilities_section: dynamic(() => import('./FacilitiesSection')),
   flight_listing: dynamic(() => import('./FlightListing')),
   flight_section: dynamic(() => import('./FlightSection')),
   grid_section: dynamic(() => import('./GridSection')),
   hero: dynamic(() => import('./Hero')),
   hotel_listing: dynamic(() => import('./HotelListing')),
   how_it_work: dynamic(() => import('./HowItWork')),
   images_section: dynamic(() => import('./ImagesSection')),
   logos_section: dynamic(() => import('./LogosSection')),
   news_section: dynamic(() => import('./NewsSection')),
   payment_section: dynamic(() => import('./PaymentSection')),
   promotion_section: dynamic(() => import('./PromotionSection')),
   service_section: dynamic(() => import('./ServiceSection')),
   special_offer: dynamic(() => import('./SpecialOffer')),
   stay_section: dynamic(() => import('./StaySection')),
   subcrible_section: dynamic(() => import('./SubcribleSection')),
   top_author: dynamic(() => import('./TopAuthor')),
   total_section: dynamic(() => import('./TotalSection')),
   tour_section: dynamic(() => import('./TourSection')),
   video_section: dynamic(() => import('./VideoSection')),
};
